// Service-worker generator: scans the built dist/ folder and emits a
// hand-rolled precache service worker (D-008 — deliberately not Workbox,
// so every line is readable and the caching model is understood, not
// imported). Depends on: node:fs/crypto. Depended on by: cli.ts,
// generate.test.ts.
//
// How updates propagate: the emitted sw.js embeds the full asset list AND a
// version hash of every file's content. Any rebuild that changes anything
// produces a byte-different sw.js; the browser notices on the next visit,
// installs the new worker (fresh cache), and activates it (old caches
// deleted). One reload later the user is on the new version.

import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { createHash } from "node:crypto";

// Must match `base` in vite.config.ts (D-012). Both files carry this note.
const BASE = "/bare-metal/";

export interface ServiceWorkerBuild {
  version: string;
  urls: string[];
  source: string;
}

/** Build sw.js source for the given dist directory. Throws if dist looks unbuilt. */
export function generateServiceWorker(
  distDir: string,
  base: string = BASE,
): ServiceWorkerBuild {
  const files = walk(distDir, "").sort();
  if (!files.includes("index.html")) {
    throw new Error(
      `${distDir}: no index.html found — run the app build before generating sw.js`,
    );
  }

  const hash = createHash("sha256");
  for (const file of files) {
    hash
      .update(file)
      .update("\0")
      .update(readFileSync(join(distDir, file)));
  }
  const version = hash.digest("hex").slice(0, 16);

  // index.html is cached under the base URL ("/bare-metal/") because that's
  // what navigations actually request; hash routes never reach the server.
  const urls = [base, ...files.filter((f) => f !== "index.html").map((f) => base + f)];

  return { version, urls, source: renderSource(version, urls, base) };
}

/** Recursive listing as base-relative POSIX paths; skips a stale sw.js. */
function walk(root: string, prefix: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(join(root, prefix))) {
    const rel = prefix === "" ? name : `${prefix}/${name}`;
    if (rel === "sw.js") continue;
    if (statSync(join(root, rel)).isDirectory()) {
      out.push(...walk(root, rel));
    } else {
      out.push(rel);
    }
  }
  return out;
}

function renderSource(version: string, urls: string[], base: string): string {
  return `// Generated by tools/sw/generate.ts — do not edit by hand.
// Precache-on-install, cache-first service worker (design: D-008).
const CACHE_NAME = "metal-${version}";
const BASE = ${JSON.stringify(base)};
const PRECACHE_URLS = ${JSON.stringify(urls, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE_URLS))
      // skipWaiting: a freshly installed version takes over without waiting
      // for every old tab to close — simplest update model for a one-person app.
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  );
});

// ignoreVary matters: crossorigin-attributed loads (the module script, the
// stylesheet) send an Origin header that precached responses' Vary headers
// would otherwise fail to match, breaking exactly those two files offline.
// Everything cached here is a same-origin static asset keyed by URL alone,
// so Vary matching adds nothing but that failure mode.
const MATCH_OPTS = { ignoreSearch: true, ignoreVary: true };

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  if (new URL(request.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.match(request, MATCH_OPTS).then((cached) => {
      if (cached) return cached;
      if (request.mode === "navigate") {
        // Every navigation (any hash route, /index.html, etc.) is the app
        // shell; serve the precached shell so offline navigation always works.
        return caches.match(BASE, MATCH_OPTS).then((shell) => shell || fetch(request));
      }
      // Not precached and not a navigation: let the network try; if it's
      // offline this fails visibly in devtools, which is correct — nothing
      // outside the precache list is promised to work offline.
      return fetch(request);
    }),
  );
});
`;
}
